# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile coverage.out

    - name: Upload coverage report to SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=TaurMorchant_qubership-core-lib-go-tmp
          -Dsonar.organization=vladislav-larkin-test-organization
          -Ssonar.host.url=https://sonarcloud.io
          -Dsonar.go.coverage.reportPaths=coverage.out
